ExamMVC/Controllers/LessonController.cs
using ExamMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging.EventSource;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json.Serialization;

namespace ExamMVC.Controllers
{
    public class LessonController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7055/api");
        private readonly HttpClient _client;

        public LessonController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<LessonsVM> Lessonlist = new List<LessonsVM>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Lessons/GetLessons").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                Lessonlist = JsonConvert.DeserializeObject<List<LessonsVM>>(data); 
            }
            return View(Lessonlist);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LessonsVM lessonsVM)
        {
           
                string data = JsonConvert.SerializeObject(lessonsVM);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Lessons/Create", content).Result;
                if (response.IsSuccessStatusCode) {  return RedirectToAction("Index"); }
            
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            LessonsVM lessons = new LessonsVM();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Lessons/GetLessonById?id=" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                lessons = JsonConvert.DeserializeObject<LessonsVM>(data);
            }
            return View(lessons);
        }
        [HttpPost]
        public IActionResult Edit(LessonsVM model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent content = new StringContent(data,Encoding.UTF8,"application/json");
            HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Lessons/Update/", content).Result;
            if (response.IsSuccessStatusCode) { return RedirectToAction("Index"); }
            return View(data);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            LessonsVM lesson = new LessonsVM();
            HttpResponseMessage response = _client.GetAsync(baseAddress + "/Lessons/Update/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                lesson = JsonConvert.DeserializeObject<LessonsVM>(data);
            }
            return View(lesson);
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/Lessons/Delete/" +id).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }    
    }
}

ExamMVC/Views/Lesson/Create.cshtml
@model ExamMVC.Models.LessonsVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="DersinKodu" class="control-label">Dərsin kodu</label>
                <input asp-for="DersinKodu" class="form-control" />
                <span asp-validation-for="DersinKodu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DersinAdi" class="control-label">Dərsin adı</label>
                <input asp-for="DersinAdi" class="form-control" />
                <span asp-validation-for="DersinAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sinifi" class="control-label">Sinifi</label>
                <input asp-for="Sinifi" class="form-control" />
                <span asp-validation-for="Sinifi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MuellimAdi" class="control-label">Müəllimin adı</label>
                <input asp-for="MuellimAdi" class="form-control" />
                <span asp-validation-for="MuellimAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MuellimSoyadi" class="control-label">Müəllimin soyadı</label>
                <input asp-for="MuellimSoyadi" class="form-control" />
                <span asp-validation-for="MuellimSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamMVC/Views/Lesson/Delete.cshtml
@model ExamMVC.Models.LessonsVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
  
   
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExamMVC/Views/Lesson/Edit.cshtml
@model ExamMVC.Models.LessonsVM

@{
    ViewData["Title"] = "Edit Lesson";
}

<h1>Edit</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div style="display:none" class="form-group">
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DersinKodu" class="control-label">Dərsin kodu</label>
                <input asp-for="DersinKodu" class="form-control" />
                <span asp-validation-for="DersinKodu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DersinAdi" class="control-label">Dərsin adı</label>
                <input asp-for="DersinAdi" class="form-control" />
                <span asp-validation-for="DersinAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sinifi" class="control-label">Sinifi</label>
                <input asp-for="Sinifi" class="form-control" />
                <span asp-validation-for="Sinifi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MuellimAdi" class="control-label">Müəllimin adı</label>
                <input asp-for="MuellimAdi" class="form-control" />
                <span asp-validation-for="MuellimAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MuellimSoyadi" class="control-label">Müəllimin soyadı</label>
                <input asp-for="MuellimSoyadi" class="form-control" />
                <span asp-validation-for="MuellimSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamMVC/Views/Lesson/Index.cshtml
@model IEnumerable<ExamMVC.Models.LessonsVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Dərslər</h1>

<p>
    <a asp-controller="Lesson" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @*@Html.DisplayNameFor(model => model.DersinKodu)*@
                <label>Dərsin kodu</label>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.DersinAdi)*@
                <label>Dərsin adı</label>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Sinifi)*@
                <label>Sinifi</label>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.MuellimAdi)*@
                <label>Müəllimin adı</label>
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.MuellimSoyadi)*@
                <label>Müəllimin soyadı</label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           @* <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.DersinKodu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DersinAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sinifi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MuellimAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MuellimSoyadi)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>